### PR TITLE
extJS tabs and about page

### PR DESCRIPTION
**Pull request by mwernimont**
@ee-usgs spent most of the day yesterday trying to get a contentEl feed into my about page yesterday, me having no javascript backgorund and my google searches coming up with nothing I was wondering if you could get it working? I have the markup in the about.js in an html: ' ' string which I'm told is not ideal. 

The tabs are working though

### CODE REVIEW

**Comment by jlucido2** [comment]
@cschroed-usgs, can you review this? Thanks

**Comment by jlucido2** [comment]
@mwernimont could you please resolve merge conflicts?

**Comment by mwernimont** [comment]
@jlucido2 I fixed the merge conflicts.  I still need to add the new html you wanted on the about page, but want to clarify a few things first.

Do not write html on the index.jsp file.  In extJS you don't write HTML that way and it's not supposed to be inside the index.jsp.  Confusing to you as I screwed up and you are still looking at my old file version which I cleaned up on this pull request.  You write the HTML in the about.js file, or at least until a dev can make a more elegant solution.

Second, mapper.jsp shouldn't exist anymore, so don't edit that file.  Index.jsp is the mapper.jsp once again.  Also confusing, but this is me correcting my mistakes of not knowing that this was an ExtJS project. 

I will add the the html you wanted added to the about.js file shortly.

**Comment by jlucido2** [comment]
@mwernimont thanks for fixing the merge conflicts and for the info on where to and not to edit html in AFINCH. I was admittedly working off of the old version. I believe that Wes will be pick up this task, hopefully today, to complete the refactor of tabs.

**Pull request merged**
